server:
  port: 8080
mybatis:
    mapper-locations: classpath:mapper/*/*.xml
spring:
  application:
    name: ServerPatrol
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    # check-process-definitions: false  #这个比较重要，不配置的话会扫描类路径下的processes下的.xml文件
  datasource:    #数据库连接信息
    url: jdbc:mysql://127.0.0.1:3306/demo_pro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    maxIdle: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 100
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#security:
  #basic:
    #enabled: false